### ISSUE TITLE
Using Glfw#get_proc_address with gl-rs is awkward (and undocumented)

### ISSUE THREAD

**Issue by HeroesGrave** [bjz/glfw-rs#130]
You can't pass self methods as arguments, so it has to be wrapped.

`gl::load_with(|procname: &str| -> Option<GLProc> { glfw.get_proc_address(procname) });`

If fixing it requires breaking thread-safety, at least a documentation update would be great.

**Comment by cmr** [comment]
I don't think this is an issue anymore, all the GL examples use this and this behavior has been in place for quite some time now.
