### ISSUE TITLE
Actual (Loyal) Binding to glfwGetPrimaryMonitor 

### ISSUE THREAD

**Issue by Binero** [bjz/glfw-rs#196]
I think the current binding to `glfwGetPrimaryMonitor` (`with_primary_monitor`) isn't really ideal. If you want an actual reference to the monitor, it requires you to put all your code using that monitor in the closure. 

Instead there should be an alternative `get_primary_monitor` which returns an `Option<Monitor>`. I am not sure if this is possible however - there must have been a reason to not stay loyal to the API, right? (lifetime issue?)

**Comment by cmr** [comment]
@Binero the video mode information is copied from the returned pointer, so there's no issue there.
