### ISSUE TITLE
Undefined reference to glfw**** error.

### ISSUE THREAD

**Issue by ZeronSix** [bjz/glfw-rs#199]
I get errors like this one when i'm trying to build an application with Cargo and glfw-rs:
```
/home/zeron/dev/gd/rocketsauce/target/deps/libglfw-cd120128a43da8e1.rlib(glfw-cd120128a43da8e1.o): In function `Window::should_close::ha545ee4ef5439dd0Juf':
glfw.rs:(.text._ZN6Window12should_close20ha545ee4ef5439dd0JufE+0x3f): undefined reference to `glfwWindowShouldClose'
```
![image](https://cloud.githubusercontent.com/assets/3040800/3735860/69095efa-1728-11e4-956a-bb65eaeb9301.png)

As you can see, there is no ```link.rs``` in the folder with the checkout of glfw-rs. Rolling back to #194 solves this problem.

**Comment by cmr** [comment]
@ZeronSix does this still repro?

**Comment by ZeronSix** [comment]
@cmr nope.
