### ISSUE TITLE
Problems with building on Windows

### ISSUE THREAD

**Issue by bvssvni** [bjz/glfw-rs#200]
See https://github.com/PistonDevelopers/piston/issues/511

I can not test this myself, because I'm running OSX. Will try engage people who are using Windows.

Somebody said they fixed it by changing from `./.build.sh` to `sh ./.build.sh`

https://github.com/bjz/glfw-rs/blob/master/Cargo.toml#L24

**Comment by cmr** [comment]
Every indication is that this is fixed.
