### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by golddranks** [bjz/glfw-rs#277]
Hi, I got this kind of error when trying to compile with the newest Rust (23th of Jan) on Mac OS X.

    Compiling glfw-sys v3.0.4 (https://github.com/servo/glfw?branch=cargo-3.0.4#d04e0643)
    error: couldn't read "/Users/drasa/.cargo/git/checkouts/glfw-4fd4342c6777c12d/cargo-3.0.4/make -f makefile.cargo": couldn't open path as file (no such file or directory (No such file or directory); path=/Users/drasa/.cargo/git/checkouts/glfw-4fd4342c6777c12d/cargo-3.0.4/make -f makefile.cargo; mode=open; access=read)
    Could not compile `glfw-sys`.

I thought it might be just my cargo files or git repository that was corrupted somehow, so I moved my .cargo directory and did a clean build, still getting the same error.

**Comment by vwim** [comment]
Yea I'm getting the same error. It has to do with recent changes in the cargo build command 
https://github.com/rust-lang/cargo/commit/0fdaf507a1f9dd9f6eb59e5579c6cf6f2cd9cff2

**Comment by davorb** [comment]
Thanks for that @vwim.

Any idea when this will get fixed?

**Comment by csherratt** [comment]
I have a patch https://github.com/servo/glfw/pull/11

**Comment by davorb** [comment]
@csherratt :+1:

**Comment by bjz** [comment]
Should be fixed now - reopen if not.
