### ISSUE TITLE
Unable to get packages from source

### ISSUE THREAD

**Issue by bvssvni** [bjz/glfw-rs#304]
`rustc 1.0.0-nightly (199bdcfef 2015-03-26) (built 2015-03-26)`

```
Unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/sven/.cargo/registry/src/github.com-1ecc6299db9ec823/glfw-sys-3.1.1/Cargo.toml`

Caused by:
  library target names cannot contain hyphens: glfw-sys
```

**Comment by IcyTesseract** [comment]
The [glfw-sys crate](https://crates.io/crates/glfw-sys) hasn't been updated to the most recent version (3.1.2) that changed the hyphen to an underscore to fix this issue.

**Comment by bjz** [comment]
I can't update it due to rust-lang/cargo#1465 :(

**Comment by bvssvni** [comment]
Seems to be fixed now!

**Comment by bvssvni** [comment]
@bjz Could you try again?

**Comment by bjz** [comment]
Done! Can you test it works for you now?

**Comment by IcyTesseract** [comment]
Works perfectly now!

**Comment by csherratt** [comment]
thanks @bjz~
