### ISSUE TITLE
OpenGL, OpenGl, and Opengl. Modify naming?

### ISSUE THREAD

**Issue by IcyTesseract** [bjz/glfw-rs#306]
I noticed that in comments, it is often times written "OpenGL." However, there is also `glfw::OpenGlProfileHint` and `glfw::WindowHint::OpenglForwardCompat`. I think it would be great to keep it the same everywhere.

**Comment by bvssvni** [comment]
`OpenGL` everywhere would be nice.

**Comment by IcyTesseract** [comment]
What about `OpenGlEs`? Should that be `OpenGLES`?

**Comment by bvssvni** [comment]
I think `OpenGLES` is fine. Thoughts?

**Comment by bjz** [comment]
Rust uses Pascal-case for initialisms. Eg. `Http` `Nasa`, etc. So I would go with `OpenGl` and `OpenGlEs`. I do agree it should be consistent though.
