### ISSUE TITLE
fmt::Debug already implemented by bitflags!

### ISSUE THREAD

**Issue by quadrupleslap** [bjz/glfw-rs#317]
In lib.rs, the following code raises a compile-time error:

```rust
impl fmt::Debug for Modifiers {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        for (i, x) in [Shift, Control, Alt, Super].iter().filter(|x| self.contains(**x)).enumerate() {
            if i != 0 { try!(write!(f, ", ")) };
            if      *x == Shift   { try!(write!(f, "Shift"   )) }
            else if *x == Control { try!(write!(f, "Control" )) }
            else if *x == Alt     { try!(write!(f, "Alt"     )) }
            else if *x == Super   { try!(write!(f, "Super"   )) }
            else                  { try!(write!(f, "???"     )) }
        }
        Ok(())
    }
}
```

I think this is because bitflags already implements the debug trait. When I remove this code, glfw compiles successfully, so can it be removed?

*I tested it on the latest Rust Nightly. Sorry if you test against stable builds or something.*

**Comment by Hammster** [comment]
Run in to the same issue on rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14) 
<bitflags macros>:8:24: 13:31 error: conflicting implementations for trait `core::fmt::Debug` [E0119]

**Comment by bvssvni** [comment]
Yeah, it can be removed.

**Comment by bvssvni** [comment]
I'll make a PR and bump it to 0.1.0 at the same time.

**Comment by quadrupleslap** [comment]
Cool. Thanks, @bvssvni !
