### ISSUE TITLE
-lglfw3 on Windows 10

### ISSUE THREAD

**Issue by dotfelixb** [bjz/glfw-rs#324]
on Windows 10 using using mingw and have added glfw files to path but still ld can not find glfw3, help

**Comment by bjz** [comment]
Unfortunately I don't use Windows. Any ideas about how we could solve this?

**Comment by nstoddard** [comment]
@dotfelixb Is this specific to Windows 10, or does it apply to all versions of Windows? I use Windows 7 and I can give some suggestions but I'm not sure if they apply to you.

On my system I need to create a directory `bin/x86_64-pc-windows-gnu` in which I put `glfw3.dll` (you may need to change the directory name slightly if you're using 32-bit etc). If this doesn't work please provide more detailed error messages.

**Comment by dotfelixb** [comment]
@nstoddard thanks, it work
